# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require 'fileutils'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def lx_prepare_ffmpeg_headers(installer)
  sandbox_root = installer.sandbox.root.to_s
  pod_root = [
    File.join(sandbox_root, 'ffmpeg-kit-ios-full', 'ffmpeg-kit-ios-full'),
    File.join(sandbox_root, 'ffmpeg-kit-ios-full'),
  ].find { |path| Dir.exist?(File.join(path, 'libavformat.xcframework')) }
  headers_root = File.join(sandbox_root, 'Headers', 'Public', 'ffmpeg-kit-ios-full')
  libraries = %w[libavcodec libavformat libavutil libswresample]

  unless pod_root
    Pod::UI.warn 'Skip FFmpeg header preparation: ffmpeg-kit-ios-full pod not found'
    return
  end

  expanded_sandbox_root = File.expand_path(sandbox_root)
  expanded_headers_root = File.expand_path(headers_root)
  unless expanded_headers_root.start_with?(expanded_sandbox_root + File::SEPARATOR)
    raise "Refusing to prepare FFmpeg headers outside Pods sandbox: #{expanded_headers_root}"
  end

  FileUtils.rm_rf(headers_root)
  libraries.each do |library|
    header_dir = [
      File.join(pod_root, "#{library}.xcframework", 'ios-arm64', "#{library}.framework", 'Headers'),
      File.join(pod_root, "#{library}.xcframework", 'ios-arm64_x86_64-simulator', "#{library}.framework", 'Headers'),
      File.join(pod_root, "#{library}.xcframework", 'ios-arm64_x86_64-maccatalyst', "#{library}.framework", 'Versions', 'A', 'Headers'),
    ].find { |path| Dir.exist?(path) }

    raise "FFmpeg headers not found for #{library}" unless header_dir

    target_dir = File.join(headers_root, library)
    FileUtils.mkdir_p(target_dir)
    FileUtils.cp_r(Dir.glob(File.join(header_dir, '*')), target_dir)
  end

  Pod::UI.puts "Prepared FFmpeg public headers: #{headers_root}".green
end

target 'LxMusicMobile' do
  config = use_native_modules!

  pod 'ffmpeg-kit-ios-full', :podspec => 'https://raw.githubusercontent.com/luthviar/ffmpeg-kit-ios-full/main/ffmpeg-kit-ios-full.podspec'

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'LxMusicMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    lx_prepare_ffmpeg_headers(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
      end
    end
  end
end
